// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/1/2024, 2:06:59 AM
const configMerger = require("/private/tmp/portfolio-the-good-one/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.27.4/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/private/tmp/portfolio-the-good-one/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/portfolio-the-good-one/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/portfolio-the-good-one/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/portfolio-the-good-one/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/portfolio-the-good-one/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/portfolio-the-good-one/plugins/**/*.{js,ts,mjs}","/private/tmp/portfolio-the-good-one/composables/**/*.{js,ts,mjs}","/private/tmp/portfolio-the-good-one/utils/**/*.{js,ts,mjs}","/private/tmp/portfolio-the-good-one/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/portfolio-the-good-one/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/portfolio-the-good-one/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["19"] = "/private/tmp/portfolio-the-good-one/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
